# Generated by Django 4.2.1 on 2023-05-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_dictionary_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='pairs',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='pairs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='page.pair'),
            preserve_default=False,
        ),
    ]
