# Generated by Django 4.2.1 on 2023-05-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_dictionary_pairs_dictionary_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='pairs',
        ),
        migrations.AddField(
            model_name='pair',
            name='dict',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='page.dictionary'),
            preserve_default=False,
        ),
    ]
