# Generated by Django 4.2.1 on 2023-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_dictionary_pairs_pair_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
