# Generated by Django 4.2.1 on 2023-05-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=64)),
                ('definition', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pair')),
            ],
        ),
    ]
