# Generated by Django 4.2.1 on 2023-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='pairs',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='pairs',
            field=models.ManyToManyField(related_name='pairs', to='main.pair'),
        ),
    ]
